### ISSUE TITLE
Build and run binary return code 137

### ISSUE THREAD

**Issue by theaveasso** [confluentinc/confluent-kafka-go#1161]
Description
===========
I want to start testing kafka producer but always fail to run from binary when I adding this package. If I run it using `go run .` it works perfectly fine.

- Operating system: MacOS M1
- Kafka version:
I ran it on docker, using docker compose
```
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```

Here is my code
```
func main() {
	producer, err := kafka.NewProducer(&kafka.ConfigMap{
        "bootstrap.servers": "localhost:29092",
    })
	if err != nil {
		log.Println(err)
	}
    fmt.Println("hello world")

    defer producer.Close()
}

```
```
/bin/sh: line 1: 55716 Killed: 9
Error: Producer process terminated with code 137
```

How to reproduce
================
1. Create a simple main.go
2. Create a new Producer
```
func main() {
	producer, err := kafka.NewProducer(&kafka.ConfigMap{
        "bootstrap.servers": "localhost:29092",
    })
	if err != nil {
		log.Println(err)
	}
    fmt.Println("hello world")

    defer producer.Close()
}
```
3. Run build
```

```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
