### ISSUE TITLE
Unable to Consume messages from Kafka Node port running in Kubernetes

### ISSUE THREAD

**Issue by anandkolli** [confluentinc/confluent-kafka-go#253]
Hi,

Description
===========
Following is my setup details:
I have a single node kubernetes cluster running single Kafka broker and zookeper.
and have exposed Node port to access kafka outside kubernetes cluster.
```
demo@demo:~$ kubectl get pod
kafka-0                  1/1       Running   0          25m
testclient               1/1       Running   0          1d
zookeeper-0         1/1       Running   0          23h

demo@demo:~$ kubectl get svc
NAME                     TYPE         CLUSTER-IP      EXTERNAL-IP   PORT(S)                                     AGE
kafka-service-hd   NodePort    10.233.46.126   <none>           30000:30000/TCP                       26m
kubernetes            ClusterIP      10.233.0.1        <none>            443/TCP                                       1d
zoo                        ClusterIP       None              <none>             2181/TCP,2888/TCP,3888/TCP   23h
```
Below is my yaml configuration file:
```
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-hd
  namespace: default
spec:
  ports:
  - nodePort: 30000
    port: 30000
    protocol: TCP
    targetPort: 9092
  selector:
    #statefulset.kubernetes.io/pod-name: kafka-0
   app: kafka
  type: NodePort


apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-service-hd
  template:
    metadata:
      annotations:
        cni: calico
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30000"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "172.27.172.79"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: KAFKA_HEAP_OPTS
          value: -Xmx256M -Xms128M
        image: docker-registry.com:5000/wurstmeister/kafka:1.0.0
        name: kafka
        ports:
        - containerPort: 9092
```

# Problem statement:

I am able to produce and consume messages outside the kubernetes cluster using Kafkacat utility.
kafkacat -b 172.27.172.79:30000 -P -t test44
Hello World

kafkacat -b 172.27.172.79:30000 -C -t test44
Hello World

But when I use confluent-kafka-go I am able to produce messages using producer example but unable to consume the messages using consumer example.

I see no error logs in Kafka or zookeper.

How to reproduce
================

Using above mentioned yaml file we can reproduce this issue.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v0.11.6 and librdkafka is latest
 - [ ] Apache Kafka broker version: wurstmeister/kafka:1.0.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: Ubuntu 16.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Please let me know if you need further information.

Thank you,
Anand
