### ISSUE TITLE
Consumer partitions assignment behaviour when new partitions are added to existing topic

### ISSUE THREAD

**Issue by PaulLiang1** [confluentinc/confluent-kafka-go#713]
Description
===========

Hi, we've observed the behaviour that consumers will not get assigned to partitions that were created after the consumer is created, not sure if this is the expected behaviour.

High level flow:

- 1. Create topic with single partition;
- 2. Create producer keep writing into topic;
- 3. Create multiple instances of consumer subscribing to the topic;
   - Only a single consumer will have partitions assignment, the rest of consumers are showing no assignment;
- 4. Increase the topic partition count;
- 5. Observed consumer assignment;
   - Idle (ones without any assignment) consumer remained unassigned. 
   - Only a subset of msg from this topic is consumed as producer were able to pick up the partitions count change and produce msg into new partitions

However we could see our "expected" behaviour by making a slight change to the flow

- ...
- 4. Increase the topic partition count;
- ->>>>> 5. Create extra instances of consumer subscribing to the topic, to force rebalance; 
- 6. Observed consumer assignment;
    -  Consumers were able to consume from newly created partitions;

How to reproduce
================

Docker compose to create a local cluster
```
---
version: '2'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker1:
    image: confluentinc/cp-server:5.5.1
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_TOOLS_LOG4J_LOGLEVEL: INFO

  broker2:
    image: confluentinc/cp-server:5.5.1
    hostname: broker2
    container_name: broker2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_TOOLS_LOG4J_LOGLEVEL: INFO

  broker3:
    image: confluentinc/cp-server:5.5.1
    hostname: broker3
    container_name: broker3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_TOOLS_LOG4J_LOGLEVEL: INFO
```

Code to reproduce:

`go.mod`
```
module test

go 1.17

require (
	github.com/confluentinc/confluent-kafka-go v1.7.0
	github.com/google/uuid v1.3.0
	github.com/sirupsen/logrus v1.8.1
)

require golang.org/x/sys v0.0.0-20211117180635-dee7805ff2e1 // indirect

```

Test code
the "working" behaviour -> remove comment for `UNCOMMENT ME` section.

```
package main

import (
	"context"
	"strconv"
	"sync/atomic"
	"time"

	"github.com/confluentinc/confluent-kafka-go/kafka"
	"github.com/google/uuid"
	"github.com/sirupsen/logrus"
)

var bootstrap = "localhost:9092"

var adminConf = &kafka.ConfigMap{
	"bootstrap.servers": bootstrap,
}

var producerConf = kafka.ConfigMap{
	"bootstrap.servers": bootstrap,
	"go.delivery.reports": true,
	"go.logs.channel.enable": true,

	// lower metadata time to let producer discover new partitions sooner
	"metadata.max.age.ms": 1000,
}

var consumerConf = &kafka.ConfigMap{
	"bootstrap.servers": bootstrap,
	"group.id":          "testcg-" + uuid.New().String(),
	"auto.offset.reset": "beginning",
	"debug": "all",

	"metadata.max.age.ms": 1000,
	"coordinator.query.interval.ms": 1000,
	"auto.commit.interval.ms": 1000,
	"partition.assignment.strategy": "roundrobin",
}

var nbMsgProduced int64 = 0
var nbMsgConsumed int64 = 0

func createTopic(admin *kafka.AdminClient, topicName string) {
	result, err := admin.CreateTopics(
		context.Background(),
		[]kafka.TopicSpecification{
			{
				Topic:             topicName,
				NumPartitions:     1,
				ReplicationFactor: 1,
			},
		},
	)
	if err != nil {
		panic(err)
	} else {
		logrus.Info("[ADMIN] Topic created: ", result)
	}
}

func produceIntoTopic(topicName string){
	producer, err := kafka.NewProducer(&producerConf)
	if err != nil {
		panic(err)
	}

	go func(){
		for log := range producer.Logs() {
			logrus.Info("[PRODUCER] producer log: ", log)
		}
	}()

	go func(){
		counter := make(map[int32]int)
		for evt := range producer.Events() {
			switch evt := evt.(type) {
			case *kafka.Message:
				atomic.AddInt64(&nbMsgProduced, 1)
				counter[evt.TopicPartition.Partition]++
				logrus.Infof("[PRODUCER] msg sent to part: %d", evt.TopicPartition.Partition)
			default:
				logrus.Infof("[PRODUCER] producer default: %v", evt)
			}
		}
	}()

	i := 0

	for {
		msg := &kafka.Message{
			TopicPartition: kafka.TopicPartition{
				Topic:     &topicName,
				Partition: kafka.PartitionAny,
			},
			Key:   []byte(uuid.New().String()),
			Value: []byte(strconv.FormatInt((int64)(i), 10)),
		}
		producer.ProduceChannel() <- msg
		time.Sleep(200 * time.Millisecond)
	}
}

func consumeFromTopic(topicName string, nbOfConsumer int) {
	for i := 0; i < nbOfConsumer; i++ {
		go func() {
			consumer, err := kafka.NewConsumer(consumerConf)
			if err != nil {
				panic(err)
			}

			go func(){
				for log := range consumer.Logs() {
					logrus.Info("[CONSUMER] log: ", log)
				}
			}()

			consumerName := consumer.String()

			err = consumer.Subscribe(
				topicName,
				func(consumer *kafka.Consumer, event kafka.Event) error {
					switch ev := event.(type) {
					case *kafka.Message:
						atomic.AddInt64(&nbMsgConsumed, 1)

						par := ev.TopicPartition.Partition
						msg := string(ev.Value)
						logrus.Infof("[Consumer] [%s], Partition [%d], recv msg: %s\n", consumerName, par, msg)
					case kafka.AssignedPartitions:
						logrus.Infof("[Consumer] [%s] AssignedPartitions: [%v]\n", consumerName, ev)

						err := consumer.Assign(ev.Partitions)
						if err != nil {
							logrus.WithError(err).Fatal("[Consumer] boom assign")
						}

					case kafka.RevokedPartitions:
						logrus.Infof("[Consumer] [%s] RevokedPartitions\n", consumerName)

						err := consumer.Unassign()
						if err != nil {
							logrus.WithError(err).Fatal("[Consumer] boom unassign")
						}
					default:
						logrus.Infof("[Consumer] [%s], DEFAULT got: %v\n", consumerName, event)
					}
					return nil
				},
			)

			if err != nil {
				panic(err)
			}

			for {
				evt := consumer.Poll(1000)
				a, err := consumer.Assignment()
				if err != nil {
					logrus.WithError(err).Fatal("[Consumer] unable to list assignment")
				}
				logrus.Infof("[Consumer] consumer %s polling, assignment: %v", consumerName, a)


				if evt == nil {
					continue
				}

				switch ev := evt.(type) {
				case *kafka.Message:
					atomic.AddInt64(&nbMsgConsumed, 1)

					par := ev.TopicPartition.Partition
					msg := string(ev.Value)
					logrus.Infof("[Consumer] [%s], Partition [%d], recv msg: %s\n", consumerName, par, msg)
				default:
					logrus.Infof("[Consumer] [%s], DEFAULT got: %v\n", consumerName, evt)
				}
			}
		}()
	}
}

func main() {
	admin, err := kafka.NewAdminClient(adminConf)
	if err != nil {
		panic(err)
	}

	nbOfConsumer := 4
	topicName := "test." + uuid.New().String()
	createTopic(admin, topicName)
	defer func(){
		_, _ = admin.DeleteTopics(context.Background(), []string{topicName})
	}()

	go produceIntoTopic(topicName)
	go consumeFromTopic(topicName, nbOfConsumer)

	time.Sleep(5 * time.Second)
	logrus.Info("bumping nb of partitions")
	for i := 2 ;i < 16 ;i ++ {
		resp, err := admin.CreatePartitions(context.Background(),
			[]kafka.PartitionsSpecification{{
				Topic:             topicName,
				IncreaseTo:        i,
			}})
		if err != nil {
			logrus.Fatal("[ADMIN] failed to bump part size", err)
		}
		logrus.Info("[ADMIN] partitions size bumped: ", resp)
		time.Sleep(3 * time.Second)
	}

	time.Sleep(30 * time.Second)

	// UNCOMMENT ME to Add more consumers to existing group to force rebalance
	//logrus.Info("ADDING NEW CONSUMERS AFTER PARTCNT BUMP")
	//go consumeFromTopic(topicName, nbOfConsumer)
	//time.Sleep(30 * time.Second)

	logrus.Info("nb of msg produced: ", atomic.LoadInt64(&nbMsgProduced))
	logrus.Info("nb of msg consumed: ", atomic.LoadInt64(&nbMsgConsumed))
}

```

----

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):  `v1.7.0` 
 - [x] Apache Kafka broker version: `Apache Kafka® 2.5.0`
 - [x] Client configuration: `ConfigMap{...}`: See attached code snippet
 - [ ] Operating system: `Darwin 11.6 (20G165)`

```
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/jinli/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wg/vb6n2_rn4d15541_yt7d_x1c0000gn/T/go-build598499305=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
 
 - [ ] Provide client logs (with `"debug": ".."` as necessary):
Logs attached:

[log.without-assignment.gz](https://github.com/confluentinc/confluent-kafka-go/files/7585742/log.without-assignment.gz)

This one we can observed consumers have no partitions assignment
```
cat log.without-assignment | grep assignment | grep polling | tail -10
time="2021-11-23T14:56:28+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-2 polling, assignment: []"
time="2021-11-23T14:56:29+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-4 polling, assignment: [test.f3fec7e9-e426-414f-aab8-f96c3304f53b[0]@stored]"
time="2021-11-23T14:56:29+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-5 polling, assignment: []"
time="2021-11-23T14:56:29+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-6 polling, assignment: []"
time="2021-11-23T14:56:29+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-2 polling, assignment: []"
time="2021-11-23T14:56:30+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-4 polling, assignment: [test.f3fec7e9-e426-414f-aab8-f96c3304f53b[0]@stored]"
time="2021-11-23T14:56:30+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-4 polling, assignment: [test.f3fec7e9-e426-414f-aab8-f96c3304f53b[0]@stored]"
time="2021-11-23T14:56:30+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-5 polling, assignment: []"
time="2021-11-23T14:56:30+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-2 polling, assignment: []"
time="2021-11-23T14:56:30+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-6 polling, assignment: []"
```

Only some msg were consumed
```
tail -2 log.without-assignment
time="2021-11-23T14:56:30+11:00" level=info msg="nb of msg produced: 385"
time="2021-11-23T14:56:30+11:00" level=info msg="nb of msg consumed: 69"
```

appears that only `consumer-4` (the one got partitions assigned in the beginning have received `PARTCNT`
```
cat log.without-assignment | grep PARTCNT | grep consumer
%7|1637639714.195|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 0 to 1
%5|1637639718.204|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 1 to 2
%5|1637639722.150|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 2 to 3
%5|1637639724.572|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 3 to 4
%5|1637639728.298|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 4 to 5
%5|1637639730.506|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 5 to 6
%5|1637639734.538|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 6 to 7
%5|1637639736.534|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 7 to 8
%5|1637639740.563|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 8 to 9
%5|1637639744.192|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 9 to 10
%5|1637639746.210|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 10 to 11
%5|1637639750.548|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 11 to 12
%5|1637639752.274|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 12 to 13
%5|1637639754.700|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 13 to 14
%5|1637639758.227|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic test.f3fec7e9-e426-414f-aab8-f96c3304f53b partition count changed from 14 to 15
```

----

[log.with-assignment.gz](https://github.com/confluentinc/confluent-kafka-go/files/7585741/log.with-assignment.gz)

This one we can observed consumers have partitions assignmentS
```
cat log.with-assignment | grep assignment | grep polling | tail -10
time="2021-11-23T14:59:04+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-8 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[4]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[12]@stored]"
time="2021-11-23T14:59:04+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-7 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[2]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[10]@stored]"
time="2021-11-23T14:59:04+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-10 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[0]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[8]@stored]"
time="2021-11-23T14:59:04+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-8 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[4]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[12]@stored]"
time="2021-11-23T14:59:05+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-6 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[7]@stored]"
time="2021-11-23T14:59:05+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-5 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[3]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[11]@stored]"
time="2021-11-23T14:59:05+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-2 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[5]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[13]@stored]"
time="2021-11-23T14:59:05+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-6 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[7]@stored]"
time="2021-11-23T14:59:05+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-4 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[1]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[9]@stored]"
time="2021-11-23T14:59:05+11:00" level=info msg="[Consumer] consumer rdkafka#consumer-7 polling, assignment: [test.bfb098c5-1d39-4261-a027-0297a5182da2[2]@stored test.bfb098c5-1d39-4261-a027-0297a5182da2[10]@stored]"
```

all produced msg were consumed
```
tail -2 log.with-assignment
time="2021-11-23T14:59:05+11:00" level=info msg="nb of msg produced: 533"
time="2021-11-23T14:59:05+11:00" level=info msg="nb of msg consumed: 533"
```

 - [ ] Provide broker log excerpts
 - [ ] Critical issue
